[[mgr.prepend_keymap]]
on = [ "g", "M" ]
run = "plugin smart-cd -- yazi-devices path"
desc = "Discos externos"

[[mgr.prepend_keymap]]
on = [ "g", "T" ]
run = "plugin smart-cd -- yazi-trash path"
desc = "Papelera"
