# Report Noctalia configuration keys that appear in both layers.
#
# Noctalia loads every *.toml in the config dir and then overlays the state-dir
# settings.toml, which the Settings UI writes and which always wins. A key
# present in both layers is shadowed: the override decides the value and the
# declarative one is dead weight, which is how a rebuild can look like it did
# nothing.
#
# Only this file is versioned. The config dir is generated by
# `programs.noctalia.settings` in modules/home/desktop.nix, and the state file is
# linked to configs/noctalia/settings.toml with mkOutOfStoreSymlink.
#
# Usage (see the `just noctalia-diff` recipe):
#   nix-instantiate --eval --raw configs/scripts/noctalia-shadowed-keys.nix \
#     --argstr declarative ~/.config/noctalia/config.toml \
#     --argstr overrides ~/.local/state/noctalia/settings.toml
{
  declarative,
  overrides,
}:
let
  join = prefix: name: if prefix == "" then name else "${prefix}.${name}";

  # Flatten nested tables into "a.b.c" -> value, so both layers can be compared
  # by key path regardless of table order or nesting.
  flatten =
    prefix: value:
    if builtins.isAttrs value then
      builtins.foldl' (acc: name: acc // flatten (join prefix name) value.${name}) { } (
        builtins.attrNames value
      )
    else
      { ${prefix} = value; };

  readToml =
    path:
    flatten "" (
      # A path that resolves into the Nix store makes readFile attach store
      # context, which builtins.fromTOML rejects.
      builtins.fromTOML (builtins.unsafeDiscardStringContext (builtins.readFile path))
    );

  declarativeKeys = readToml declarative;
  overrideKeys = readToml overrides;

  shadowed = builtins.sort builtins.lessThan (
    builtins.filter (key: declarativeKeys ? ${key}) (builtins.attrNames overrideKeys)
  );

  line =
    key:
    "  ${key}\n"
    + "    declarative: ${builtins.toJSON declarativeKeys.${key}}\n"
    + "    overrides:   ${builtins.toJSON overrideKeys.${key}}\n";

  report =
    if shadowed == [ ] then
      "No shadowed Noctalia keys: the override layer sets nothing the declarative config already sets.\n"
    else
      "Shadowed Noctalia keys (the override layer wins, the declarative value is dead):\n"
      + builtins.concatStringsSep "" (builtins.map line shadowed)
      + "\nKeep the key in configs/noctalia/settings.toml if the UI owns it, or drop it from programs.noctalia.settings.\n";
in
report
